### Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url=jdbc:postgresql://localhost:5432/locktestdatabase
#spring.datasource.username=postgres
#spring.datasource.password=testtest
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:log4jdbc:h2:mem:testdb
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# For Hibernate 5 (Spring Boot 2.x)
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# For Hibernate 6 (Spring Boot 3.x)
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# log4jdbc configuration
logging.level.jdbc.sqlonly=INFO
logging.level.jdbc.sqltiming=OFF
logging.level.jdbc.audit=OFF
logging.level.jdbc.resultset=OFF
logging.level.jdbc.resultsettable=OFF
logging.level.jdbc.connection=OFF
logging.level.log4jdbc.log4j2=OFF

# Custom log4jdbc properties to simplify logs
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.dump.sql.maxlinelength=0
log4jdbc.dump.sql.addsemicolon=true
log4jdbc.log4j2.properties.file=log4jdbc.log4j2.properties